### ISSUE TITLE
QR Code selector not working

### ISSUE THREAD

**Issue by wizardkitty** [mdziekon/OctoPrint-SpoolManager#37]
The QR Code system generates fine but this issue lies in how each QR code is used.

If I scan Spool 1 I get Spool 1, But If I scan Spool 2 I get the Correct DB number but the Name and Selected spool is Spool 1.

To Duplicate just set up two spools with different names. and select spool 2.

Then Scan Spool 2 QR Code and you should see the Name of Spool 1 and that the selection is now Spool 1.

**Comment by mdziekon** [comment]
Hi @wizardkitty, thanks for the report. By chance, do you know whether this bug existed in the previous, pre-fork version, or is this something unique to this fork?

**Comment by mdziekon** [comment]
Looks like pre-fork version (1.7.0) did handle it fine, although looking at the backend code seems to indicate that there was a frontend fix applied (intentionally or not, not sure), since the API call itself always sets the first ID as currently selected spool, but then the frontend "fixes" it by reselecting by spool ID from the current URL.

Will mark as `regression`, but I'll also try to reduce unnecessary reselections as well.

**Comment by mdziekon** [comment]
The issue should be fixed now (see #40 for more details).
Could you please verify on your end that the issue has been fixed, by using assets from the draft release?

https://github.com/mdziekon/OctoPrint-SpoolManager/releases/tag/2.0.0-draft

**Comment by mdziekon** [comment]
@wizardkitty
The issue should be fixed now (see #40 for more details).
Could you please verify on your end that the issue has been fixed, by using assets from the draft release?

https://github.com/mdziekon/OctoPrint-SpoolManager/releases/tag/2.0.0-draft

**Comment by wizardkitty** [comment]
Sorry for the late reply but it does work now!
