### ISSUE TITLE
BUG: When Scanning QR Code of different spools, only spool 1 is selected for printing

### ISSUE THREAD

**Issue by ScottGibb** [mdziekon/OctoPrint-SpoolManager#52]
Issue
When using the plugin, I found that no matter which spool QR Code I scanned, the plugin would always select spool 1 in the database for printing. I'm running an iPhone 13 with the built-in QR Code Scanner, opening the webpage in Safari. When I scanned spool 2 in the database through the UI, the following link was created:

http://wanhaoprint.local/plugin/SpoolManager/selectSpoolByQRCode/2

It would seem that the URL is being created correctly, however possibly not being handled on the other side correctly.
 Reading the releases, it seems like this issue was already fixed in this fork. However it doesn't seem to be working for me.

### Steps to Repeat
- Use an iPhone 13 QR Code Scanner
- Scan the QR Code on a spool that isn't the first in the database.
- Plugin selects spool 1 for printing

### Hardware/Software Setup
- OctoPrint-SpoolManager v1.8
- Octoprint Version Version 1.9.3
- Raspberry Pi 3

### Plugin Manager Snippet
![image](https://github.com/mdziekon/OctoPrint-SpoolManager/assets/44235263/dcaaf34b-139a-4dae-9991-6f54f8447936)

**Comment by mdziekon** [comment]
This has been fixed in this PR: https://github.com/mdziekon/OctoPrint-SpoolManager/pull/40
First reported here: https://github.com/mdziekon/OctoPrint-SpoolManager/issues/37

The reason why this has not worked for you is because you've used a version which does not contain a fix yet (version 1.8.0, the fix is in unrelease 2.0.0). Therefore, I'll close this issue as "duplicate", and maybe try to release the 2.0.0 version soon.

---

I've seen you've mentioned another fork which "works for you". It seems this fork is based on my work here, it just so happens that "latest version" there is equal to my most recent work, with some additional changes related to postgres.

**Comment by ScottGibb** [comment]
@mdziekon Thank you so much for highlighting this, been stuck in my brain for weeks. Doing little investigations here and there
